### ISSUE TITLE
Cityscapes val SOTA results not found in the paper

### ISSUE THREAD

**Issue by eldar** [SHI-Labs/OneFormer#112]
Dear all,

Thanks for your excellent paper and provided code. It is currently #1 on Cityscapes val instance segmentation leaderboard with AP 50.6 https://paperswithcode.com/sota/instance-segmentation-on-cityscapes-val however I could not find this result in the paper. On GitHub the best model seems to reach 48.9 (https://github.com/SHI-Labs/OneFormer#cityscapes) - 1.5% below than the number on PapersWithCode. Is there an updated config for the SOTA result reaching 50.6 AP?

**Comment by praeclarumjj3** [comment]
Hi @eldar, thanks for your interest.

The model can be found in the readme on the `internimage` branch: https://github.com/SHI-Labs/OneFormer/blob/internimage/README.md#cityscapes

**Comment by eldar** [comment]
Thanks so much for the quick response! This is resolved then.
