### ISSUE TITLE
RuntimeError: Not implemented on the CPU (When running example notebook)

### ISSUE THREAD

**Issue by Robotatron** [SHI-Labs/OneFormer#15]
Using your example notebook getting an error `RuntimeError: Not implemented on the CPU `

![image](https://user-images.githubusercontent.com/95919873/205785385-216f8e91-2d4e-4fb4-9fa9-7580dda4ad35.png)

Changing **cfg.MODEL.DEVICE** and **cpu_device = torch.device("cpu")** to "cuda" throws a different error

![image](https://user-images.githubusercontent.com/95919873/205785566-dec10cda-9117-499c-a9d5-97bfa8732f96.png)

**Comment by praeclarumjj3** [comment]
Hi @Robotatron, thanks for your interest in our work. 

It is strange that you are encountering this error, as the notebook works perfectly fine when I execute the cells. It would be best if you do not replace `cpu` with `cuda` in `cpu_device = torch.device("cpu")` as we need to transfer the result to the CPU to convert it into a NumPy array. Are you sure you did not make any other changes to the notebook?

I would like you to confirm if you are cloning the `OneFormer-Colab` repo. If you still face issues, you may look at the [Roboflow youtube video covering our demo](https://youtu.be/_Zr1pOi7Chw).

<img width="1305" alt="Screenshot 2022-12-05 at 6 06 07 PM" src="https://user-images.githubusercontent.com/54928629/205790918-362e5fce-43b5-470f-89ba-a71232db9e8a.png">

**Comment by praeclarumjj3** [comment]
Closing this issue for now. Feel free to reopen if you face any issues.

**Comment by Robotatron** [comment]
> Are you sure you did not make any other changes to the notebook?

I am using the notebook locally, in a freshly created conda env following your guides.

**Comment by Robotatron** [comment]
I am using your exact code - https://pastebin.com/bn0v0Ce5

Using CUDA 11.3 Pytorch install, however "nvidia-smi" shows me I have CUDA 11.2 installed. And under 
`cat /usr/local/cuda/version.txt` it says "11.0". Could this be a problem?

![image](https://user-images.githubusercontent.com/95919873/206307685-905fc57d-b5ad-4a42-8b3d-d7495166caac.png)

**Comment by Robotatron** [comment]
@praeclarumjj3 Thank you very much, it was indeed an issue with PyTorch installed with CUDA 11.3. Using PyTorch with 11.1 on a machine with 11.2 solved the issue!

![image](https://user-images.githubusercontent.com/95919873/209477937-1c1d83d8-c9eb-465e-9a8f-e92b278d7225.png)
