### ISSUE TITLE
Convert Model to TensorRT

### ISSUE THREAD

**Issue by abhigoku10** [SHI-Labs/OneFormer#16]
@honghuis  @SkalskiP  thanks for sharing the source code , Just wante dto knw can we convert this model to Tensorrt or ONNX format ? if so please share the conversion and inference script 

Thanks in advance

**Comment by praeclarumjj3** [comment]
Hi @abhigoku10, thanks for your interest in our work. We don't have an already written script to convert the model to TensorRT or ONNX format.

I think the conversion should be pretty straightforward. You can try following the script shared by @SkalskiP (thanks for sharing!). If you need any assistance from our side, please let us know.

**Comment by praeclarumjj3** [comment]
Feel free to re-open the issue if you need any help.

**Comment by tomhog** [comment]
i've managed to export the model to onnx, there's a few issues at the moment to get it working

1. I wasn't sure how to get MSDeformAttnFunction to export (Think it's possible) so commented it out and used the ms_deform_attn_core_pytorch fallback
2. Onnx expects just "image" in the input dictionary, there was no way to pass "task" so I just did a check if it was missing and added one to the dict so it didn't crash
3. Onnx expects only a list of tensors as output so as I was only interested in semantic I just output that
4. There's an op used, can't remember which, that pytorch 1.10 onnx export didn't support. You need at least opset 16, so I had to switch to pytorch 1.12.1, torchvision 0.13.1, then build detectron2 from source as couldn't seem to find a compatible prebuilt.

With those changes the export_model.py script worked with a few small changes and I was able to use the model in onnxruntime.

**Comment by fernandorovai** [comment]
Hi @tomhog, could you please share the changes you did for exporting to onnx? Thanks a ton!

**Comment by tomhog** [comment]
Hi @fernandorovai 

Certainly, though as I said it's a bit of a mess at the moment. I will tidy it up, I just needed to prove it can work before moving forward. Also worth noting I'm not sure if the onnx file would work on GPU, not tried yet.

[hack to ms_deform_attn so it doesn't use the custom op (and why it might not work on gpu)](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-c0f93371b74aed0aad80021edb2203e685c16e90bda2851ed0f97199b49afc98)

[Changes to oneformer model to handle missing task in input dict, and only output one task type](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-b6ca9ea09be4cdb1116a7bb0a532106edf174370d438f4643cdf4ed7869d727a)

[script to export the onnx file](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-cc07ca1c73c4d34e26bf89858985dd4be9148640d36902dd942b6034bd560dd6)

[demo using the onnx file](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-e5be7b8762289fa61ce6c439baa500c08126ca841c00b77fb0944a3295745be0)

Export command would look something like
```
python ./demo/export_model.py --config-file ./configs/ade20k/convnext/oneformer_convnext_large_bs16_160k_2gpu.yaml \
   --format onnx \
   --export-method tracing \
   --sample-image ../datasets/512x512.jpg \
   --run-eval \
   --output ./output \
   MODEL.IS_TRAIN False MODEL.IS_DEMO True MODEL.WEIGHTS ./output/ade20k_convnext_large/model_0099999.pth
```

Currently the dimensions of the sample image need to match the dimensions the model was trained at.

I think the rest of that commit it just noise (I was having odd issues with pybind11) and a few of my own bash scripts for convenience.

If it works for you please let me know and maybe we could work on a cleaner approach to add official support to OneFormer.

Tom
PS
Remember from my post above you have to use pytorch 1.12.1, torchvision 0.13.1

**Comment by John0x** [comment]
@tomhog have you tested gpu support yet?
I was hoping to use OneFormer as an onnx model, but not having GPU support would mean, that I have to use a different model or implement my own.

**Comment by AAAstorga** [comment]
I'm very new to ML, so I apologize if my question is naive. Is it possible to convert this model to PyTorch Lite? I'm curious to see if it's possible to use this model with https://playtorch.dev/.

I was hoping to follow this: https://playtorch.dev/docs/tutorials/prepare-custom-model/

But I don't think it's that straightforward. I would appreciate any guidance if possible! Thank you.

**Comment by praeclarumjj3** [comment]
Hi @AAAstorga, thanks for your interest in our work. 

You may want to follow the tutorial on using DETR with PlayTorch, as OneFormer and DETR are both built using detectron2.
https://playtorch.dev/docs/tutorials/snacks/object-detection/.

Also, it might be better to create a new issue for PlayTorch.

**Comment by praeclarumjj3** [comment]
You can refer PyTorch tutorials: https://pytorch.org/tutorials/

**Comment by ZhouYC-X** [comment]
@tomhog Thank you for your sharing of onnx export. I test it and can infer when dimensions of the sample image can match the dimensions the model was trained. I tried to add dynamic axes and success export onnx file. However, the infer with onnx is faild, the error infromation is as follows. I wonder if you have sove the  dynamic axes.  I would appreciate it if anyone can provide some tips! Thank you.

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_2134' Status Message: Add_2134: left operand cannot broadcast on dim 1 LeftShape: {1,32256,1,3,1,2}, RightShape: {1,38304,8,3,4,2}

**Comment by hengguo-boop** [comment]
@tomhog  I'm using your code to convert onnx and I'm having this problem is there any way to fix it look forward to your reply!
`Traceback (most recent call last):
  File "./demo/export_model.py", line 249, in <module>
    exported_model = export_tracing(torch_model, sample_inputs)
  File "./demo/export_model.py", line 154, in export_tracing
    torch.onnx.export(traceable_model, (image,), f, verbose=True, opset_version=16, do_constant_folding=False, input_names=["input"], output_names=["output"], dynamic_axes={})#STABLE_ONNX_OPSET_VERSION)
  File "/home/lbm/lbm_src/conda_env/env/oneformer/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/lbm/lbm_src/conda_env/env/oneformer/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/lbm/lbm_src/conda_env/env/oneformer/lib/python3.8/site-packages/torch/onnx/utils.py", line 1110, in _export
    ) = graph._export_onnx(  # type: ignore[attr-defined]
RuntimeError: ONNX export failed: Couldn't export Python operator NATTEN2DQKRPBFunction
`

**Comment by lianglilong-gloritytech** [comment]
> Hi @fernandorovai
> 
> Certainly, though as I said it's a bit of a mess at the moment. I will tidy it up, I just needed to prove it can work before moving forward. Also worth noting I'm not sure if the onnx file would work on GPU, not tried yet.
> 
> [hack to ms_deform_attn so it doesn't use the custom op (and why it might not work on gpu)](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-c0f93371b74aed0aad80021edb2203e685c16e90bda2851ed0f97199b49afc98)
> 
> [Changes to oneformer model to handle missing task in input dict, and only output one task type](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-b6ca9ea09be4cdb1116a7bb0a532106edf174370d438f4643cdf4ed7869d727a)
> 
> [script to export the onnx file](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-cc07ca1c73c4d34e26bf89858985dd4be9148640d36902dd942b6034bd560dd6)
> 
> [demo using the onnx file](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-e5be7b8762289fa61ce6c439baa500c08126ca841c00b77fb0944a3295745be0)
> 
> Export command would look something like
> 
> ```
> python ./demo/export_model.py --config-file ./configs/ade20k/convnext/oneformer_convnext_large_bs16_160k_2gpu.yaml \
>    --format onnx \
>    --export-method tracing \
>    --sample-image ../datasets/512x512.jpg \
>    --run-eval \
>    --output ./output \
>    MODEL.IS_TRAIN False MODEL.IS_DEMO True MODEL.WEIGHTS ./output/ade20k_convnext_large/model_0099999.pth
> ```
> 
> Currently the dimensions of the sample image need to match the dimensions the model was trained at.
> 
> I think the rest of that commit it just noise (I was having odd issues with pybind11) and a few of my own bash scripts for convenience.
> 
> If it works for you please let me know and maybe we could work on a cleaner approach to add official support to OneFormer.
> 
> Tom PS Remember from my post above you have to use pytorch 1.12.1, torchvision 0.13.1

@tomhog Hi, sorry to bother you. Have you ever encountered the problem of significant drop in accuracy when using the onnx model to predict? I compared the output with the same input, the difference is in MSDeformAttnFunction.apply and ms_deform_attn_core_pytorch.
Picture 1 below is a comparison of the output of onnx using cuda and the original model.
Picture 2 below is a comparison of the output of onnx when using CPU and the original model.

Obviously the accuracy is slightly worse when using CPU, but it is directly 0 when using CUDA. Have you encountered this problem? Or can you provide some suggestions?
![screenshot-3](https://github.com/SHI-Labs/OneFormer/assets/134380502/2cb58d7f-5b32-4be3-8a67-dcbfb3aba0c4)
![screenshot-4](https://github.com/SHI-Labs/OneFormer/assets/134380502/b39a97a6-8e6f-4c43-bde6-c3aa5939bb67)

**Comment by roboserg** [comment]
Was anyone able to run the ONNX model on the GPU and having the same metrics as with Pytorch inference (i.e. AP50) ?
@tomhog

**Comment by xuyuxiu83** [comment]
> Hi @fernandorovai
> 
> Certainly, though as I said it's a bit of a mess at the moment. I will tidy it up, I just needed to prove it can work before moving forward. Also worth noting I'm not sure if the onnx file would work on GPU, not tried yet.
> 
> [hack to ms_deform_attn so it doesn't use the custom op (and why it might not work on gpu)](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-c0f93371b74aed0aad80021edb2203e685c16e90bda2851ed0f97199b49afc98)
> 
> [Changes to oneformer model to handle missing task in input dict, and only output one task type](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-b6ca9ea09be4cdb1116a7bb0a532106edf174370d438f4643cdf4ed7869d727a)
> 
> [script to export the onnx file](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-cc07ca1c73c4d34e26bf89858985dd4be9148640d36902dd942b6034bd560dd6)
> 
> [demo using the onnx file](https://github.com/broadlume/OneFormer/commit/1c463c4a6d690f2b97a777b0cacbf100087e4e53#diff-e5be7b8762289fa61ce6c439baa500c08126ca841c00b77fb0944a3295745be0)
> 
> Export command would look something like
> 
> ```
> python ./demo/export_model.py --config-file ./configs/ade20k/convnext/oneformer_convnext_large_bs16_160k_2gpu.yaml \
>    --format onnx \
>    --export-method tracing \
>    --sample-image ../datasets/512x512.jpg \
>    --run-eval \
>    --output ./output \
>    MODEL.IS_TRAIN False MODEL.IS_DEMO True MODEL.WEIGHTS ./output/ade20k_convnext_large/model_0099999.pth
> ```
> 
> Currently the dimensions of the sample image need to match the dimensions the model was trained at.
> 
> I think the rest of that commit it just noise (I was having odd issues with pybind11) and a few of my own bash scripts for convenience.
> 
> If it works for you please let me know and maybe we could work on a cleaner approach to add official support to OneFormer.
> 
> Tom PS Remember from my post above you have to use pytorch 1.12.1, torchvision 0.13.1

Thank you very much for providing the ONNX format conversion code! I have successfully obtained the ONNX file and performed inference. Have you tried converting the model to TensorRT format? I encountered an issue where the BiasGelu operator is not supported during this process. How can I resolve this?
![1ee37751-d658-41e6-8673-9690f3eb264f](https://github.com/SHI-Labs/OneFormer/assets/126574371/2bbb0a30-0656-4ef5-9bb3-83c64d899639)
