### ISSUE TITLE
how to use pretrained model?

### ISSUE THREAD

**Issue by StawEndl** [SHI-Labs/OneFormer#19]
hi, i want to use pretained model for new trainning, how should i do? i want to trainning with dataset B, and i want to use model_0159999.pth which is producted at trainning on dataset A, as the pretrained model.

**Comment by praeclarumjj3** [comment]
Hi, you can directly set the MODEL.WEIGHTS as `model_0159999.pth` to use it as the pretrained checkpoint.

```bash
python train_net.py --dist-url 'tcp://127.0.0.1:50163' \
    --num-gpus 8 \
    --config-file <path-to-config>  \
    MODEL.WEIGHTS model_0159999.pth \
    OUTPUT_DIR <output_dir> WANDB.NAME <name>
```
