### ISSUE TITLE
Poor performance for instance task

### ISSUE THREAD

**Issue by assia855** [SHI-Labs/OneFormer#22]
Thanks for sharing this work. I test the model and I have a similar result for panoptic and semantic but I have a poor performance for instance task. 
![output](https://user-images.githubusercontent.com/62453226/214606289-d4aa530b-37b5-4dfe-b7d2-eabc4bf39e3a.png)

I tried to test the model with the swin backbone but I have this error:

`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

I would like to train the model on custom datasets for instance segmentation can you provide please a demo for training on custom datasets.

Thanks in advance

**Comment by praeclarumjj3** [comment]
Hi @assia855, thanks for your interest in our work. Could you share the command that you executed for the instance segmentation result?

> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

This error usually means that the checkpoint is not downloaded completely. Did you download the checkpoint file correctly? It should be around 900 MB in size for the Swin-L backbone.

> I would like to train the model on custom datasets for instance segmentation can you provide please a demo for training on custom datasets.

We share guidelines to train OneFormer on custom datasets [here](https://github.com/SHI-Labs/OneFormer/tree/main/datasets/custom_datasets). You may also refer to #17.

**Comment by assia855** [comment]
Hi @praeclarumjj3  I implement the colab demo locally and I had this output provide above for instance task.  My environment:

`
Build cuda_11.3.r11.3
torch:  1.10 ; cuda:  1.10.1
detectron2: 0.6`

I still have this error when I select swin True and launch the cell to load the models. Which checkpoint I should download for this one please.

`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

Thanks for sharing the guideline.

**Comment by praeclarumjj3** [comment]
@assia855 are you sure you did not make any changes (setup, predictor loading) to the colab code? I can successfully run the demos for all tasks using our [colab demo](https://colab.research.google.com/github/SHI-Labs/OneFormer/blob/main/colab/oneformer_colab.ipynb).

**Comment by assia855** [comment]
Thanks @praeclarumjj3  I will retry.
