### ISSUE TITLE
How can we add Validation Dataset for periodic evaluation during training ?

### ISSUE THREAD

**Issue by vineetsharma14** [SHI-Labs/OneFormer#31]
Hello There,

Fristly, thanks for the sharing the amazing work !

I am using OneFormer for Instance Segmentation Task on custom dataset. 

I read the #17 and used the "_InstanceCOCOCustomNewBaselineDatasetMapper_" from the _instance_coco_custom_dataset_mapper.py_; and I am able to train the model on my dataset.

I was trying to figure out - if I can get the inference results on the Validation Dataset periodically, says every 100 iterations.

I modified the cfg as below -

`cfg.DATASETS.TEST = "CustomInstSegVAL"`
`cfg.TEST.EVAL_PERIOD = 100`
 

I created a overridden version of the `build_test_loader` function using the _InstanceCOCOCustomNewBaselineDatasetMapper_ as below -

`def build_test_loader(cos, cfg, dataset_name):`
`    val_ampper = InstanceCOCOCustomNewBaselineDatasetMapper(cfg, is_train = True)`
`    return build_detection_test_loader(DatasetCatalog.get('CustomInstSegVal'), mapper=val_mapper)`

NOTE: if I set `is_train = False` in `val_mapper = InstanceCOCOCustomNewBaselineDatasetMapper(cfg, is_train = True)`, then it throws AssertionError from the `build_transform_gen function` of _InstanceCOCOCustomNewBaselineDatasetMapper_.

If I set `is_train = True` in `val_mapper = InstanceCOCOCustomNewBaselineDatasetMapper(cfg, is_train = True)`, then it throws AssertionError from pycocotools/coco.py > stating _"AssertionError: Results do not correspond to current coco set"_

Can you please guide me as to how we can use the Validation Dataset to test the models performance during the training.

Thanks !

**Comment by praeclarumjj3** [comment]
Hi @vineetsharma14, thanks for your interest in our work. 

You don't need to prepare a custom `data_mapper` for validation. You must define a `val` split while registering your custom dataset, and everything should work fine. You may take a look at [defining](https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py#L36-L39) and [registering](https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py#L310) of the `coco_panoptic` dataset for reference.

**Comment by vineetsharma14** [comment]
Thanks for your response.

I have checked the 2 links for [defining](https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py#L36-L39) and [registering](https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py#L310) of the coco_panoptic dataset, which you had shared for reference.


However, things are not very clear. Do we need to write a custom "register_coco_instance_annos_seg.py" similar to "register_coco_panoptic_annos_semseg.py"?


**NOTE : I am using a dataset in COCO format only for instance segmentation.** 

As mentioned in #17, I have used the `register_coco_instance` from `detectron2.data.datasets`.


Can you please elaborate on what one needs to do to add validations dataset ?


Thanks !

**Comment by praeclarumjj3** [comment]
>Do we need to write a custom "register_coco_instance_annos_seg.py" similar to "register_coco_panoptic_annos_semseg.py"?

Hi @vineetsharma14, sorry for not getting back to you earlier. Yes, you need to write a custom `register_dataset` file with your train and val splits when using a custom dataset. As you mentioned that your dataset is already in the COCO format and training on instance segmentation, [`register_coco_panoptic2instance.py`](https://github.com/SHI-Labs/OneFormer/blob/main/oneformer/data/datasets/register_coco_panoptic2instance.py#L27-L29) might be a better reference for you. You will need to replace the image and JSON paths with those of your custom dataset.

https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/oneformer/data/datasets/register_coco_panoptic2instance.py#L27-L29

Something like:

```python
_PREDEFINED_SPLITS_CUSTOM_DATASET = {
    "<YOUR_DATASET>_val": (<path-to-images>, <path-to-JSON-file>),
}


def register_instances_cutom_dataset(root):
    for key, (image_root, json_file) in _PREDEFINED_SPLITS_CUSTOM_DATASET.items():
        # Assume pre-defined datasets live in `./datasets`.
        register_coco_instances(
            key,
            _get_builtin_metadata(<dataset-name>),
            os.path.join(root, json_file) if "://" not in json_file else json_file,
            os.path.join(root, image_root),
        )
```

**Comment by vineetsharma14** [comment]
Thanks @praeclarumjj3 for the guidance. Really appreciate it !

**Comment by Pari-singh** [comment]
What is the dataset_mapper_name: coco_unified_lsj and oneformer_unified in the config files?

**Comment by Pari-singh** [comment]
Hi @vineetsharma14 were you able to successfully train on the custom instance segmentation data alone, following the steps above?
I am hitting an error in line 339, in build_batch_data_loader
    data_loader = torchdata.DataLoader(
  File "/home/auro/miniconda3/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 183, in __init__
    assert prefetch_factor > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

(Did get the data setup working, atleast got the data distribution printed right as verification). 

I noticed semantic_seg.py being called during the process but my dataset is similar to coco instance (I followed each step above)

Would appreciate any help! @praeclarumjj3

**Comment by Pari-singh** [comment]
Hi @vineetsharma14 I am facing the same issue. @praeclarumjj3 I made the changes as you suggested above, for mentioning the split while registering the data at once. But if I dont modify build_test_loader to define my custom mapper there, it throws error saying dataset "" is not defined, even though I am clearly passing the DATASETS.TEST_INSTANCE in the config.
