### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by sushilkhadkaanon** [SHI-Labs/OneFormer#32]
Could you please provide detailed instructions on training for a custom dataset?  Read the [Custom training](https://github.com/SHI-Labs/OneFormer/tree/main/datasets/custom_datasets) page but couldn't understand anything.

**Comment by praeclarumjj3** [comment]
Hi @sushilkhadkaanon, thanks for your interest in our work.

I believe the instructions are comprehensive enough, as other users (#17, #31) have been able to train on custom datasets following my instructions. I suggest you spend some more time trying to understand [registering custom datasets in Detectron2](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) and then try preparing a [custom dataset mapper](https://github.com/SHI-Labs/OneFormer/tree/main/datasets/custom_datasets). 

Let me know if you have any specific issues.

**Comment by sushilkhadkaanon** [comment]
Hi! Thanks, I really appreciate your work. I tried following your instructions. 
I added InstanceCOCOCustomNewBaselineDatasetMapper in build_train_loader of train_net.py
But where do I register my dataset? 
`  #
    
    
    
    from detectron2.data.datasets import register_coco_instances
    
    register_coco_instances("my_dataset_train", {}, "_annotations.coco.json", "custom_data/train")
    register_coco_instances("my_dataset_test", {}, "_annotations.coco.json", "custom_data/train")
    
    metadata_train = MetadataCatalog.get("my_dataset_train")
    cfg.DATASETS.TRAIN = ("my_dataset_train",)
    cfg.DATASETS.TEST = ("my_dataset_test",)
    
    cfg.SOLVER.MAX_ITER = 5 
    
    ` 
    
    Added this inside main function in train_net.py.
    Now this is giving me `ModuleNotFoundError: 

      Please compile MultiScaleDeformableAttention CUDA op with the following commands:
	\`cd mask2former/modeling/pixel_decoder/ops\`
	\`sh make.sh\``

**Comment by praeclarumjj3** [comment]
You can look at [`register_ade20k_instance.py`](https://github.com/SHI-Labs/OneFormer/blob/main/oneformer/data/datasets/register_ade20k_instance.py) for reference. You need to create a similar file for your dataset. Also, the official detectron2 guide on [adding custom datasets](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) is quite detailed.
