### ISSUE TITLE
Huggingface demo output error, please check

### ISSUE THREAD

**Issue by ymzlygw** [SHI-Labs/OneFormer#35]
Hi, Thanks for your work.
When I using demo in huggingface, it just has error info.
Could you please check that?

**Comment by praeclarumjj3** [comment]
Hi @ymzlygw, thanks for your interest in our work and for bringing this to our attention.

The demo is up and working again now. Please try it on your end too.

<img width="1296" alt="Screenshot 2023-03-21 at 2 58 04 PM" src="https://user-images.githubusercontent.com/54928629/226565359-9ef5ee16-31d7-40e3-8898-3c8db7189f18.png">

**Comment by ymzlygw** [comment]
Thanks! It works!

**Comment by ymzlygw** [comment]
> Hi @ymzlygw, thanks for your interest in our work and for bringing this to our attention.
> 
> The demo is up and working again now. Please try it on your end too.
> 
> <img alt="Screenshot 2023-03-21 at 2 58 04 PM" width="1296" src="https://user-images.githubusercontent.com/54928629/226565359-9ef5ee16-31d7-40e3-8898-3c8db7189f18.png">

Thanks! It works!
