### ISSUE TITLE
To get a segmentation label map from the model output

### ISSUE THREAD

**Issue by rose-jinyang** [SHI-Labs/OneFormer#38]
Hello
How are you?
Thanks for contributing to this project.
Could u guide me to get a segmentation label map from the model output?

**Comment by praeclarumjj3** [comment]
Hi @rose-jinyang, thanks for your interest in our work.

You can run the demo script to visualize the segmentation label map from the model output. You may add an `output_folder` argument while initializing an evaluator object to specify the path where the segmentation label maps for the model's predictions should be saved.

https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/train_net.py#L358

becomes:

```python
 evaluator = cls.build_evaluator(cfg, dataset_name, output_folder=<PATH-TO-YOUR-FOLDER>)
 ```

**Comment by rose-jinyang** [comment]
Thanks for your reply.
I want to get the segmentation label map as numpy array on python code.

**Comment by praeclarumjj3** [comment]
Could you specify the segmentation task: semantic, instance, or panoptic?

**Comment by rose-jinyang** [comment]
I want to get instance segmentation label maps.

**Comment by rose-jinyang** [comment]
Or I want to get boxes, scores, class_ids, mask binary maps.

**Comment by praeclarumjj3** [comment]
Thanks for the clarification. You can obtain tensors (convert into np.array) for those from the instance predictions directly.

```python
instances = predictions["instances"]
boxes = instances.pred_boxes
scores = instances.scores
classes = instances.pred_classes
masks = instances.pred_masks
```

Note that to obtain boxes, you will need to see `DETECTION_ON` as `True` in the config.
https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/configs/coco/oneformer_R50_bs16_50ep.yaml#L54

**Comment by rose-jinyang** [comment]
Thanks

**Comment by rose-jinyang** [comment]
Hello
I have more questions.
![image](https://user-images.githubusercontent.com/47862419/227849277-b191ca3f-23bd-4eb2-81c8-9d9574eeb0e9.png)
I checked the detectorn2's output format in their help.
Here what is the N?
Does the "pred_masks" mean a binary mask for each instance object in the rectangle regions by the "pred_boxes"?

**Comment by praeclarumjj3** [comment]
Hi @rose-jinyang, the `N` denotes the number of segmented regions (or object masks) in the image.

> Does the "pred_masks" mean a binary mask for each instance object in the rectangle regions by the "pred_boxes"?

Yes, you are correct.

**Comment by rose-jinyang** [comment]
Hi
Thanks for your kind help.
I want to get one segmentation map containing all the class labels rather than binary mask for each instance.
How can I get it?
