### ISSUE TITLE
Bounding box for each instance

### ISSUE THREAD

**Issue by rose-jinyang** [SHI-Labs/OneFormer#41]
Hello
How are you?
Thanks for contributing to this project.
I found that the demo script does NOT output bounding boxes for each instance in panoptic/instance segmentation.
Could u guide me how to get the bounding boxes?

**Comment by praeclarumjj3** [comment]
Hi @rose-jinyang, please set `DETECTION_ON` as True in the config to visualize bounding boxes.

https://github.com/SHI-Labs/OneFormer/blob/761189909f392a110a4ead574d85ed3a17fbc8a7/configs/coco/oneformer_R50_bs16_50ep.yaml#L54

**Comment by rose-jinyang** [comment]
It works now. Thanks

**Comment by prashantmetadome** [comment]
how to do the same for the huggingface integration. I could not find the relevant config.
