### ISSUE TITLE
real-time or  video segmentation

### ISSUE THREAD

**Issue by wangchao0720** [SHI-Labs/OneFormer#47]
****hello,  can this structure be used for **real-time** segmentation or video segmentation****

**Comment by praeclarumjj3** [comment]
Hi @wangchao0720, yes, you can use a lightweight backbone for real-time segmentation. Note that a Swin-L OneFormer outputs result at ~15 FPS on a single RTX A6000 GPU. So, a lighter backbone like ResNet-50 will give an even faster inference speed. You can perform video segmentation in a frame-by-frame manner.
