### ISSUE TITLE
losses  are zero during training on custom dataset

### ISSUE THREAD

**Issue by sahityabonumaddi** [SHI-Labs/OneFormer#56]
this is the output after running oneformer model on custom dataset  for panoptic segmentation
dice loss and contrastive losses are zero  after 4999 iterations.
any help  @praeclarumjj3 

wandb: Run summary:
wandb:              data_time 0.00161
wandb:            eta_seconds 72805.84595
wandb:                     lr 0.0001
wandb:                   time 0.46956
wandb:          train/loss_ce 0.00051
wandb:        train/loss_ce_0 0.00188
wandb:        train/loss_ce_1 0.00058
wandb:        train/loss_ce_2 0.00071
wandb:        train/loss_ce_3 0.00056
wandb:        train/loss_ce_4 0.00058
wandb:        train/loss_ce_5 0.00056
wandb:        train/loss_ce_6 0.0005
wandb:        train/loss_ce_7 0.00065
wandb:        train/loss_ce_8 0.00066
wandb: train/loss_contrastive 0.0
wandb:        train/loss_dice 0.0
wandb:      train/loss_dice_0 0.0
wandb:      train/loss_dice_1 0.0
wandb:      train/loss_dice_2 0.0
wandb:      train/loss_dice_3 0.0
wandb:      train/loss_dice_4 0.0
wandb:      train/loss_dice_5 0.0
wandb:      train/loss_dice_6 0.0
wandb:      train/loss_dice_7 0.0
wandb:      train/loss_dice_8 0.0
wandb:        train/loss_mask 0.0
wandb:      train/loss_mask_0 0.0
wandb:      train/loss_mask_1 0.0
wandb:      train/loss_mask_2 0.0
wandb:      train/loss_mask_3 0.0
wandb:      train/loss_mask_4 0.0
wandb:      train/loss_mask_5 0.0
wandb:      train/loss_mask_6 0.0
wandb:      train/loss_mask_7 0.0
wandb:      train/loss_mask_8 0.0
wandb:       train/total_loss 0.00719

**Comment by praeclarumjj3** [comment]
Hi @sahityabonumaddi, you might need to check for any bugs in your code while setting up the custom dataset. Or there might be some overfitting. I can't help you just by looking at the zero-loss values.
