### ISSUE TITLE
Pickled yaml warning?  What gives?

### ISSUE THREAD

**Issue by GeneralAwareness** [SHI-Labs/OneFormer#57]
WARNING:fvcore.common.config:Loading config D:\stable-diffusion-webui-ux\extensions\sd-webui-controlnet\annotator\oneformer\configs/ade20k/oneformer_swin_large_IN21k_384_bs16_160k.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

What gives with this as no one I spoke to had ever seen this before.  I never even knew a .yaml could be pickled before now, and even if this is a false flag it is the first time anyone has seen it before.

**Comment by praeclarumjj3** [comment]
Hi @GeneralAwareness, the yaml loading code is based on the one used in detectron2. I suggest you open the issue there.

**Comment by GeneralAwareness** [comment]
Why am I being tossed around by all of you?  No offence, but fuck it I just never use it so no loss as I am tired of being tossed around from one place to another to now another.
