### ISSUE TITLE
error in ms_deformable_im2col_cuda: too many resources requested for launch

### ISSUE THREAD

**Issue by AxuJIuyc** [SHI-Labs/OneFormer#6]
Hello!
I am trying to run a demo for a single image. I use "oneformer_dinat_large_IN21k_384_bs16_160k.yaml" as config file and "250_16_dinat_l_oneformer_ade20k_160k.pth" as model weights. When I run the demo.py, I see the following lines: "error in ms_deformable_im2col_cuda: too many resources requested for launch" and the code ends up saving {task}.jpg without significant information.
The error string occurs when executing the timeline code in demo/defaults.py: line 81 "predictions = self.model([inputs])[0]"

**Comment by praeclarumjj3** [comment]
Hi @AxuJIuyc, thanks for your interest in our work.

The error is probably related to an issue with your GPU. Could you provide the following information?

- PyTorch Version (with CUDA version)
- GPU type 

Also, could you look at [this issue](https://github.com/pytorch/pytorch/issues/7680#issuecomment-390729076) and check if reducing the maximum number of threads might fix the problem?

If nothing works, please share the complete trackback for the error.
