### ISSUE TITLE
Image contains class names

### ISSUE THREAD

**Issue by oguzhannysr** [SHI-Labs/OneFormer#61]
hello, when I examined my output results, I saw that the class names are also in the image. How can I remove them from the image?

**Comment by praeclarumjj3** [comment]
Hi @oguzhannysr, thanks for your interest. You can comment out all calls of `self.draw_test(..)` in `demo/visualizer.py` to remove the text from the output.

https://github.com/SHI-Labs/OneFormer/blob/7145cdaeea50968239055bcb0618d32bd306590f/demo/visualizer.py#L828-L834
