### ISSUE TITLE
Issue with detectron 2 installation 

### ISSUE THREAD

**Issue by EthanAbitbol3** [SHI-Labs/OneFormer#63]
First, thank you for your work. 
I am trying to do the installation but i got this issue : 
![image](https://github.com/SHI-Labs/OneFormer/assets/43862103/72342034-470a-4e8b-b2a4-5f6bbfdbe162)

Do you have any idea how i can solve this ? 

Thank you again !

**Comment by praeclarumjj3** [comment]
Hi @EthanAbitbol3, thanks for pointing this out. 

I guess it's an issue with `pip.` Could you try the following python script to build detectron2 from the source?

```python
import sys, os, distutils.core, subprocess
if not os.path.exists('./detectron2'):
    subprocess.run(['git', 'clone', 'https://github.com/facebookresearch/detectron2'])
dist = distutils.core.run_setup("./detectron2/setup.py")
for x in dist.install_requires:
    subprocess.run(['python', '-m', 'pip', 'install', x])
sys.path.insert(0, os.path.abspath('./detectron2'))
```

**Comment by EthanAbitbol3** [comment]
thank you for your answer ! I did what you told me : 
![image](https://github.com/SHI-Labs/OneFormer/assets/43862103/38a68c7c-d7ec-40dd-b5f6-3aa10593420f)
as you can see in the picture, the detectron import work but the google.collab does not work, so i tried : 
![image](https://github.com/SHI-Labs/OneFormer/assets/43862103/91ab66ad-d17b-4711-b418-a183d993477a)
I comment it to continue but : 
![image](https://github.com/SHI-Labs/OneFormer/assets/43862103/742cf1aa-8921-4096-bcde-891f127e54b6)
what do you think about that ? 
Sorry for bothering you and thank you for your help !

**Comment by EthanAbitbol3** [comment]
to solve the issue of color map i put demo.colormap in demo\visualizer.py

**Comment by EthanAbitbol3** [comment]
I have torch 1.10.1 but i got this error :
![image](https://github.com/SHI-Labs/OneFormer/assets/43862103/2ab420c0-093a-4118-937c-715a4b83e8aa)
I trie different version of pytorch but still the same issue ...
