### ISSUE TITLE
[Issue] error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by momo1986** [SHI-Labs/OneFormer#67]
My command is` python train_net.py --config-file configs/cityscapes/swin/oneformer_swin_large_bs16_90k.yaml --eval-only MODEL.IS_TRAIN False MODEL.WEIGHTS 250_16_swin_l_oneformer_cityscapes_90k.pth  MODEL.TEST.TASK semantic `

Is there an issue related to CUDA?

Thanks & Regards!
Momo

**Comment by praeclarumjj3** [comment]
Hi @momo1986, did you setup the CUDA kernel for the MSDeformAttn module? Please look at the last step in the [installation instructions](https://github.com/SHI-Labs/OneFormer/blob/main/INSTALL.md#setup-instructions).

**Comment by praeclarumjj3** [comment]
Feel free to re-open if you are still facing any issues.

**Comment by momo1986** [comment]
Hi, my CUDA is 11.1, set CUDA_HOME to /usr/local/cuda-11.1.

Then I follows the installing structions.

Still has a problem:
error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device
