### ISSUE TITLE
Is it possible to run the code without wandb? 

### ISSUE THREAD

**Issue by asmith26** [SHI-Labs/OneFormer#7]
Hi there, thanks very much for publishing this repo, it looks very interesting.

I'm trying to follow the [installation instructions](https://github.com/SHI-Labs/OneFormer/blob/main/INSTALL.md) but due to the CPU architecture of the system I'm using, I don't think I'll be able to use `wandb` (I don't have an account with them so thought I'd try run it locally):

```bash
$ wandb server start
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/ppc64le) and no specific platform was requested
```

**Is it possible to run the code without wandb?** 

Thanks for any help! :)

**Comment by praeclarumjj3** [comment]
Hi @asmith26, thanks for your interest in our work.

If you want to run the code without wandb, you need to remove the following lines in `train_net.py`.

https://github.com/SHI-Labs/OneFormer/blob/d20a596fef5568e2c19bd14eaa208fb2896e772d/train_net.py#L191
https://github.com/SHI-Labs/OneFormer/blob/d20a596fef5568e2c19bd14eaa208fb2896e772d/train_net.py#L397-L398

**Comment by Robotatron** [comment]
It works, thanks @praeclarumjj3 

But there is no log data for tensorboard. I am wondering was tensorboard logging disabled for Oneformer on purpose? Usually Detectron2, and models build on top of it (Mask2Former, MaskDINO, etc) all log tensorboard data by default.

**Comment by praeclarumjj3** [comment]
Hi @Robotatron, to avoid redundancy, we do not use tensorboard logging as we already use wandb logging. You can re-enable Tensorboard logging with minimal changes:

- import `TensorboardXWriter` from `detectron2.utils.events` here:
https://github.com/SHI-Labs/OneFormer/blob/5e04c9aaffd9bc73020d2238757f62346fe778c0/train_net.py#L65

- replace `WandbWriter()` with `TensorboardXWriter(self.cfg.OUTPUT_DIR)`:
https://github.com/SHI-Labs/OneFormer/blob/5e04c9aaffd9bc73020d2238757f62346fe778c0/train_net.py#L191
