### ISSUE TITLE
Can I retrain a oneformer model only for semantic seg? 

### ISSUE THREAD

**Issue by RYHSmmc** [SHI-Labs/OneFormer#70]

**Comment by praeclarumjj3** [comment]
Hi @RYHSmmc, thanks for your interest in our work. Yes, you can. There are two cases:

- **If you have panoptic annotations**: Set `TASK_PROB.SEMANTIC` as `1.0` in the config.
https://github.com/SHI-Labs/OneFormer/blob/56799ef9e02968af4c7793b30deabcbeec29ffc0/configs/ade20k/Base-ADE20K-UnifiedSegmentation.yaml#L56

- **If you only have semantic annotations**: You can use the [custom semantic dataset mapper](https://github.com/SHI-Labs/OneFormer/blob/main/datasets/custom_datasets/semantic_oneformer_custom_dataset_mapper.py#L230).

**Comment by praeclarumjj3** [comment]
Feel free to re-open if you are still facing any issues.
