### ISSUE TITLE
Onnx conversion and C++ implementation.

### ISSUE THREAD

**Issue by itguru2015** [SHI-Labs/OneFormer#72]
Thank you for your efforts in OneFormer's research work.
I am currently trying to implement the Instance segmentation in C++ using oneformer.

1. The easiest way is to convert the oneformer model to onnx and use it.
I have looked carefully at what has been discussed here and I have tried converting, but failed.
https://github.com/SHI-Labs/OneFormer/issues/16

This is the screenshot.
![image](https://github.com/SHI-Labs/OneFormer/assets/45484140/0eba31e7-35c2-4284-b931-f857b443a76f)

2. Next I try to use the libtorch library, but I haven't been successful yet.

My question are:
1. Are there any achievements in the work to convert the model to onnx?
2. Is there a demo source code for c++ implementation?

Thanks in advance

**Comment by praeclarumjj3** [comment]
Hi, @janebittner09, thanks for your interest. Unfortunately, I haven't had the opportunity to work on the conversion to ONNX format myself yet. Presently, we don't have any plans to work on a C++ demo.

About the error you are facing, what is the GPU memory on your machine? It seems you need more memory which might be leading to the `Segmentation Fault` error.
