### ISSUE TITLE
Detectron2 and Openmmlab question

### ISSUE THREAD

**Issue by LiJiahang617** [SHI-Labs/OneFormer#73]
Hi, thanks for the great work, but i'm wondering why you chose Detectron2 as your base, cause i found that in your previous work in 2022: SeMask Segmentation, you used Openmmlab as your backend. Why you chose Detectron2 this time. Is it because Openmmlab is hard to use or some other reason? Did Openmmlab has any bugs in OneFormer code implementation?

**Comment by praeclarumjj3** [comment]
Hi @LiJiahang617, thanks for your interest in OneFormer. 

We build OneFormer on top of DETR-based works (MaskFormer/Mask2Former), all implemented initially with the Detectron2 library. As for SeMask, SeMask-FPN uses the segmentation library. However, SeMask-Mask2Former uses the Detectron2 library. I want to emphasize that SeMask is an add-on for any semantic segmentation hierarchical transformer backbones and can be used with any library.

**Comment by LiJiahang617** [comment]
Thanks for your reply, now i get rhe point of your choice, thanks again!



---Original---
From: "Jitesh ***@***.***&gt;
Date: Tue, Jun 27, 2023 19:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SHI-Labs/OneFormer] Detectron2 and Openmmlab question (Issue#73)




 
Hi @LiJiahang617, thanks for your interest in OneFormer.
 
We build OneFormer on top of DETR-based works (MaskFormer/Mask2Former), all implemented initially with the Detectron2 library. As for SeMask, SeMask-FPN uses the segmentation library. However, SeMask-Mask2Former uses the Detectron2 library. I want to emphasize that SeMask is an add-on for any semantic segmentation hierarchical transformer backbones and can be used with any library.
