### ISSUE TITLE
PQ value for each validation image

### ISSUE THREAD

**Issue by sumanth2002629** [SHI-Labs/OneFormer#75]
Is there any way in which I can get the PQ value for each validation image of the cityscapes dataset while running the evaluation??

When I run the evaluation, I get the combined metrics. Where do I see the metrics of each validation image?

**Comment by praeclarumjj3** [comment]
Closing, feel free to reopen.

**Comment by HaonanZhao1** [comment]
Hi. Is there any way to find the code that transfers the prediction results to the PQ evaluator on Cityscapes dataset?
