### ISSUE TITLE
Demo Colab Link broken

### ISSUE THREAD

**Issue by wardcarson** [SHI-Labs/OneFormer#79]
I was looking to try out the demo and noticed the link to the colab for it leads to an image inpainting notebook, which is weird because I had clicked on it a few days ago and it brought me to the right notebook. Any help would be appreciated

Link it brought me to:

https://colab.research.google.com/github/SHI-Labs/FcF-Inpainting/blob/main/colab/FcF_Inpainting.ipynb

**Comment by praeclarumjj3** [comment]
Hi @wardcarson; thanks for pointing this out! 

The issue was with the link inside the [demo directory's Readme](https://github.com/SHI-Labs/OneFormer/tree/main/demo#oneformer-demo). The link in the main readme works fine. Anyway, it's fixed now. Again, thanks for pointing it out.
