### ISSUE TITLE
inquery about ade20k caption label 

### ISSUE THREAD

**Issue by Mollylulu** [SHI-Labs/OneFormer#8]
Hi, thanks for your great work. I did not find the caption-related annotations on the ADE20K website, could you point out how to get them?  or how to generate them?

**Comment by praeclarumjj3** [comment]
Hi @Mollylulu, thanks for your interest in our work.

We do not use captions to train or test OneFormer. Their mention was there from a previous experimental setting. I have removed them from the file list. Thanks for pointing it out to me.

**Comment by Mollylulu** [comment]
noted :)
