### ISSUE TITLE
If annotation format of my dataset is png instead of json, I want to know how to change the format   

### ISSUE THREAD

**Issue by 15114842111** [SHI-Labs/OneFormer#86]
Sorry to bother, If annotation format of my dataset is png instead of json, I want to know how to change the format

**Comment by praeclarumjj3** [comment]
I am sorry but could you elaborate? Would you like to convert your dataset into COCO format? If yes, you may look at the sample JSON data for COCO, extract classes and masks, and save it in JSON format. A simple Google search should give you various tutorials for the same. Let me know if you have any specific questions related to OneFormer.
