### ISSUE TITLE
demo.py问题

### ISSUE THREAD

**Issue by wangchao0720** [SHI-Labs/OneFormer#89]
from detectron2.projects.deeplab import add_deeplab_config这段代码，我在https://github.com/facebookresearch/detectron2/tree/main/detectron2中没有找到deeplab下的add_deeplab_config函数，请问博主，这是为什么呢

**Comment by praeclarumjj3** [comment]
It's here: https://github.com/facebookresearch/detectron2/blob/main/projects/DeepLab/deeplab/__init__.py
